### PR TITLE
quick-start: update firewall tutorials to reflect nftables-based firewall commands

### PR DESCRIPTION
**Pull request by NickAnderegg**
I've written a new `nftables`-oriented firewall quick start guide, which aims to provide enough context for the reader to reason about the new firewall backend. I did *a lot* of testing with different variations on a fresh qotom box that was attached to my existing network on the WAN side and my laptop on the LAN side; this is the variant that touches on all the most important concepts while meeting the needs of a basic NAT gateway configuration.

The original sources for the base of my configuration were the [current nftables firewall examples](https://docs.vyos.io/en/latest/configuration/firewall/general.html#operation-mode-firewall) and the examples in netfilter configuration. The new nftables firewall could definitely use significantly more documentation, but I'll keep my PRs atomic.

Original message for reference:

> ~~Is anyone already focused on translating all of the `iptables`-based firewall CLI examples to `nftables`-based examples? If not, I'll take a swing at it this weekend. I'm a docs person who is currently migrating my home network from EdgeOS to VyOS, so I'll already be needing to figure out how most of the guides translate to the new API.~~

### CODE REVIEW

**Comment by aslanvyos** [comment]
Hi, @NickAnderegg it is good news.

**Comment by fett0** [comment]
@nicolas-fort

**Comment by NickAnderegg** [comment]
I think this one is ready for review. The linter is going to fail, but it's because there's a super longer URL on the `general-legacy.rst` page.

**Comment by nicolas-fort** [comment]
I like this one
:+1:

**Pull request merged**
