### PR TITLE
added dhcp-server configuration option 43 to point UniFI devices to a…

### PR DESCRIPTION
**Pull request by joolli**
… controller on an external network

### CODE REVIEW

**Comment by c-po** [comment]
Thanks for this contribution. With the latest VyOS 1.4 rolling you could even run that controller on VyOS itself.

I have a question about: `set service dhcp-server shared-network-name example-scope subnet 10.1.1.0/24 static-mapping unifi-controller static-mapping-parameters 'option ubnt.unifi-address 172.16.1.10;'`

Should this not rather be written as:
```
set service dhcp-server shared-network-name example-scope subnet 10.1.1.0/24 static-mapping Access-Point mac-address x:x:x:x:x:x
set service dhcp-server shared-network-name example-scope subnet 10.1.1.0/24 static-mapping Access-Point ip-address 172.16.1.20
set service dhcp-server shared-network-name example-scope subnet 10.1.1.0/24 static-mapping Access-Point static-mapping-parameters 'option ubnt.unifi-address 172.16.1.10;'
```

**Comment by joolli** [comment]
Then you're assigning a static address. That's not the goal. It's just to
send this option to all connecting clients. Those that have no use for it
will throw it away, UniFi devices will use it to know where to send the
"inform"

Þann mið., 19. maí 2021, 19:09 Christian Poessinger skrifaði <
***@***.***>:

**Comment by c-po** [comment]
Given your example the following configuration is rendered:

```
### Autogenerated by dhcp_server.py ###

# For options please consult the following website:
# https://www.isc.org/wp-content/uploads/2017/08/dhcp43options.html
#
# log-facility local7;


ddns-update-style none;
option rfc3442-static-route code 121 = array of integer 8;
option windows-static-route code 249 = array of integer 8;
option wpad-url code 252 = text;

# The following 7 line(s) have been added as
# global-parameters in the CLI and have not been validated !!!
option space ubnt;
option ubnt.unifi-address code 1 = ip-address;
class "ubnt" {
match if substring (option vendor-class-identifier, 0, 4) = "ubnt";
option vendor-class-identifier "ubnt";
vendor-option-space ubnt;
}


# Shared network configration(s)
shared-network foo {
    subnet 172.18.201.0 netmask 255.255.255.0 {
        option routers 172.18.201.1;
        default-lease-time 86400;
        max-lease-time 86400;
        host foo_unifi-controller {
            hardware ethernet ;
            # The following 1 line(s) were added
            # as static-mapping-parameters in the CLI and have not been validated
            option ubnt.unifi-address 172.16.1.10;
        }
        range 172.18.201.10 172.18.201.20;
    }
    on commit {
        set shared-networkname = "foo";
    }
}
```

Somehow this still looks odd to me.

I'd expect the `option ubnt.unifi-address 172.16.1.10;` option under the `subnet { }` section which could be done by:
`set service dhcp-server shared-network-name foo subnet 172.18.201.0/24 subnet-parameters  'option ubnt.unifi-address 172.16.1.10;'`

So it is really send to all clients.

This would render instead:

```
cpo@LR1.wue3# cat /run/dhcp-server/dhcpd.conf
### Autogenerated by dhcp_server.py ###

# For options please consult the following website:
# https://www.isc.org/wp-content/uploads/2017/08/dhcp43options.html
#
# log-facility local7;


ddns-update-style none;
option rfc3442-static-route code 121 = array of integer 8;
option windows-static-route code 249 = array of integer 8;
option wpad-url code 252 = text;

# The following 7 line(s) have been added as
# global-parameters in the CLI and have not been validated !!!
option space ubnt;
option ubnt.unifi-address code 1 = ip-address;
class "ubnt" {
match if substring (option vendor-class-identifier, 0, 4) = "ubnt";
option vendor-class-identifier "ubnt";
vendor-option-space ubnt;
}


# Shared network configration(s)
shared-network foo {
    subnet 172.18.201.0 netmask 255.255.255.0 {
        option routers 172.18.201.1;
        # The following 1 line(s) were added as
        # subnet-parameters in the CLI and have not been validated!!!
        option ubnt.unifi-address 172.16.1.10;
        default-lease-time 86400;
        max-lease-time 86400;
        range 172.18.201.10 172.18.201.20;
    }
    on commit {
        set shared-networkname = "foo";
    }
}
```

Or am I still missing something here?

**Comment by joolli** [comment]
No, you're not. I also found it odd, but did not find the option you
pointed out and the device informed correctly. Your rendered config is
correct according to the UniFI documentation. Should I change it and
re-commit?

Þann fim., 20. maí 2021, 06:39 Christian Poessinger skrifaði <
***@***.***>:

**Comment by c-po** [comment]
Please update this PR with the new example config. Thanks!

**Comment by joolli** [comment]
Thanks for the evaluation. It's been updated.

**Pull request merged**
