### PR TITLE
T2810: Docs for vpn anyconnect-server

### PR DESCRIPTION
**Pull request by RasPutinnn**
This documentation describes how to configure AnyConnect-Server on VyOS

### CODE REVIEW

**Review by dmbaturin — CHANGES_REQUESTED** [review]
Cisco consistently spells it "AnyConnect" in all their publications. I believe we should do the same for the sake of consistency.

Other than this minor issue, this is sure a welcome addition, I'm happy to merge once spelling consistency is fixed.

**Comment by andamasov** [comment]
How about use AnyConnect-compatible server
We need to add a disclaimer about trademarks @dmbaturin

**Comment by dmbaturin** [comment]
@syncer I'm only talking about capitalization: "AnyConnect-compatible" over "anyconnect-compatible" etc.

Regarding trademarks, I believe we indeed should add a disclaimer somewhere, as a CYA measure.

**Comment by RasPutinnn** [comment]
I performed the requested change. Please let me know if can´t see the changes reflected on github.

**Comment by kroy-the-rabbit** [comment]
I'm of the opinion here that we shouldn't say "AnyConnect" at all, except in the documentation of to say "AnyConnect compatible".  Similar to what the original https://www.infradead.org/openconnect/ documentation mentions.

Unfortunately, I think the whole documentation for it needs to be refactored AND the underlying code. I think even

```
set vpn anyconnect ...
```
Is opening ourselves up to potential future issues. 

Moreso since as the above link mentions, OpenConnect works with more than just AnyConnect.  And 2), could we even get away with using the name:


```
set vpn openconnect
```

Wouldn't `ssl-vpn` or something be better?

**Comment by RasPutinnn** [comment]
I performed the requested change. Please let me know if the changes are not reflected on github.

**Pull request merged**
