### PR TITLE
Revert "Correct small typos; add matching examples"

### PR DESCRIPTION
**Pull request by currite**
Pleae revert Pull Request from @hlmtre

The typo correction is fine, the rest is wrong.

### CODE REVIEW

**Comment by dmbaturin** [comment]
They looked fine at a glance... deeper look never harms.

**Comment by currite** [comment]
@dmbaturing Do you know if there is any way I could be notified about some specific parts of the documentation?

**Comment by hlmtre** [comment]
Well poop. @currite, what's wrong with the other changes? Unless things
have changed since or I haven't noticed it not working, that is working in
my environment.

**Comment by dmbaturin** [comment]
Ok then. @currite could you create better examples or elaborate why @hlmtre's examples were bad?
I have to admit I haven't touched QoS in a while so "fine at a glance" is best assessment I can really give.

**Comment by currite** [comment]
Hi @hlmtre 

Thank you for the typo correction! But the rest was not ok...

This is what is technically wrong in your configuration:

**1.** Class 2 misses share allocation (bandwidth)
**2.** Class 2 misses ceiling (you set priority)
**3.** Class 5 misses matching criteria

Besides the technical mistakes, there are other issues:

**4.** What is the purpose of setting such a short queue-limit (16 packets) when using Stochastic Fairness Queueing? I don't understand. I don't think that is a "simple" example, I think that would require an explanation.

**5.** When contributing to the configuration, I think it would be better to respect the numbering and position of the other classes in the configuration, just for the sake of didactics.

Maybe your intention was to show other matching criteria? That is ok, but since there are so many different filter cases and they all can be applied to different policies, [the documentation just lists them](https://docs.vyos.io/en/latest/qos.html#matching-traffic).

**Comment by currite** [comment]
@dmbaturin @hlmtre 

Yes, I think it is very easy to have a QoS not properly configured and live with it without noticing it. I have had that!

**Comment by hlmtre** [comment]
@currite my intention was to show other matching criteria, specifically protocol instead of IP address, which I think can be more useful for allowing bulk data to consume a majority of available bandwidth while still giving very important packets immediate attention for a positive user experience.

Thank you, genuinely, for the explanation. I will be the first to admit that QoS and tc underneath it is something I am not an expert in. I will now make your corrections in my own VyOS router 😃

**Comment by hlmtre** [comment]
@currite serves me right for not reading all of it slowly and carefully. In my own environment, I _have_ share allocations, ceilings, and matching criteria for all of the classes I missed in the correction. I only included the chunks needed to show the examples I intended to show, and not the rest of the settings that are needed for a class to be useful. I will submit a (hopefully) correct PR soon.

**Comment by currite** [comment]
@hlmtre 
I have just pushed [a new PR](https://github.com/vyos/vyos-documentation/pull/302) adding port and DSCP filters to the Shaper example.

**Pull request merged**
