### PR TITLE
add reference to /etc/hosts

### PR DESCRIPTION
**Pull request by b-**
This mainly for search engine optimization -- it took me too much effort to get the correct results I wanted by searching the Internet for `vyos hosts file`

### CODE REVIEW

**Review by dmbaturin — CHANGES_REQUESTED** [review]
Maybe mention explicitly that if one was going to edit `/etc/hosts`, they should not do it and should use those commands instead?

**Comment by b-** [comment]
Good idea, because me knowing about the fact that VyOS will regenerate it on boot was the only reason I didn't just blindly try editing hosts manually anyway!

**Comment by b-** [comment]
hm, I clicked the "re-request review" button and it "removed request for [rebortg](https://github.com/rebortg)", so just in case here's a ping

**Comment by b-** [comment]
sorry for the extra commit, i put an extra comma in that was bothering me

**Pull request merged**
