### PR TITLE
T6410: applied reusable workflows (auto-author-assign,check-pr-conflicts,lint-doc)

### PR DESCRIPTION
**Pull request by kumvijaya**
Applied reusable workflows
- auto-author-assign
- check-pr-conflicts
- lint-doc

## Change Summary

Applied reusable workflows (auto-author-assign, check-pr-conflicts, lint-doc)

## Related Task(s)

* https://vyos.dev/T6410

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-documentation/blob/current/CONTRIBUTING.md) document

### CODE REVIEW

**Comment by kumvijaya** [comment]
@Mergifyio backport sagitta

**Comment by kumvijaya** [comment]
@Mergifyio backport equuleus

**Review by rebortg — CHANGES_REQUESTED** [review]
when you delete the reviewers.yml and i'm not in the vyos/reviewers group, will I still get the information about the review?

**Comment by kumvijaya** [comment]
@rebortg 
for now, I have added you to codeowners file.

**Pull request merged**
