### PR TITLE
routing/ip-commands: add a collection of IPv4 and IPv6 commands missi…

### PR DESCRIPTION
**Pull request by currite**
…ng in the manual.

### CODE REVIEW

**Comment by currite** [comment]
Hey @dmbaturin , thank you for merging! But it looks like something went wrong: the published page is not showing the code blocks at IPv4 operational commands.

**Comment by dmbaturin** [comment]
Yeah, I only looked at the content and it looked good to me. It can be hard to predict how it builds...

**Comment by currite** [comment]
Yes, something went wrong when building. And I am seeing now it has just happened the same with the crux branch!

**Comment by currite** [comment]
Mystery found @dmbaturin, it was my fault, sorry!

@c-po found where the problem was: I did not add "none" to the code-block directive.

What I don't understand is why everything looked ok when building it locally.

**Pull request merged**
