### PR TITLE
Split dhcp-relay docs out of dhcp-server page (Was: "Remove empty, duplicate "dhcp-relay" page")

### PR DESCRIPTION
**Pull request by KF5JWC**
~~dhcp-relay is covered in the dhcp-server page, and the dhcp-relay section in that page is already listed in the index.~~

### CODE REVIEW

**Comment by c-po** [comment]
Probably better move the DHCP relay stuff to its dedicated page/file?

**Comment by KF5JWC** [comment]
Not picky about that being a more appropriate focus.

Let me know if the more appropriate resolution to this is a different focus.
The question asked makes unclear the preferred convention for the docs.

**Comment by c-po** [comment]
@rebortg what would be the best move here?

**Comment by rebortg** [comment]
If we strictly follow the [guideline](https://docs.vyos.io/en/latest/documentation.html#page-content), dhcp-relay should be on an extra page. I know that makes sometimes more and sometimes less sense. It should be consistent if possible.

precisely should there be a page also for v6

```
vyos@RTR-VYOS# set service
Possible completions:
 > dhcp-relay   Host Configuration Protocol (DHCP) relay agent
 > dhcp-server  Dynamic Host Configuration Protocol (DHCP) for DHCP server
 > dhcpv6-relay DHCPv6 Relay Agent parameters
 > dhcpv6-server  DHCP for IPv6 (DHCPv6) server
```

**Comment by c-po** [comment]
@KF5JWC could you please do the split?

**Comment by KF5JWC** [comment]
PR modified, dhcp-relay split out from dhcp-server.

---

Also, removed the `_dhcp` tag due to sphinx complaints:

```
WARNING: duplicate label dhcp
```

Each page has its own command as its tag.

**Comment by rebortg** [comment]
great, thank you very much

**Pull request merged**
