### PR TITLE
mpls-conf: T915: Added documentation for LDP import and export

### PR DESCRIPTION
**Pull request by Cheeze-It**
Added examples for the new import and export functionality that
LDP is now getting on https://github.com/vyos/vyos-1x/pull/639

### CODE REVIEW

**Comment by rebortg** [comment]
Hi, would you please resolve the conflicts.

**Comment by Cheeze-It** [comment]
> 
> 
> Hi, would you please resolve the conflicts.

Most certainly, but it doesn't say to me what is conflicting. Are you able to see the conflicts?

**Comment by rebortg** [comment]
i merged a big change yesterday and the file you changes have an other location now. I think you don't pull the changes before your commit.

**Comment by Cheeze-It** [comment]
Ahh yes that would do it. 

Should I close this PR, rebase, re-PR?

**Comment by Cheeze-It** [comment]
Will close PR, and rebase, and submit another. Give me a little bit.

**Pull request closed without merging**
