### PR TITLE
Log privacy

### PR DESCRIPTION
**Pull request by currite**

### CODE REVIEW

**Comment by c-po** [comment]
Somehow all your PRs ship the same commits - looks like something went wrong way big time here. closing this.

**Comment by currite** [comment]
Hi @c-po 
Please let me know if you have any suggestion to avoid that. I don't know why that happened.
I will try again to do the PRs.

**Comment by c-po** [comment]
This can only have been added that after you send your first PR you created additional local branches, starting always from your latest PR branch.

Instead those branches should all have been started back by your `origin/master` branch - or send all changes in one PR instead of several.

Work is not lost locally - you can create a new branch and cherry-pick the commits locally and send new PR.

**Comment by currite** [comment]
Thank you!! I did not kwow what the reason was nor what to do now.

**Pull request closed without merging**
