### PR TITLE
Tcpdump tshark

### PR DESCRIPTION
**Pull request by currite**

### CODE REVIEW

**Comment by currite** [comment]
No file change in those old five first commits. The only commit that includes a file change is the last one (commit 6a3add7).

**Comment by currite** [comment]
Reopened it to see if after merge those commits disappear.

**Comment by c-po** [comment]
Too many reverse merges for this simple change, This could have been avoided by using `git rebase`.

I now cherry-picked commit fd1bbb3bc28aae214f06e1dd931a7d5ce3c87558 by hand. Thanks!

**Comment by currite** [comment]
Sorry about that @c-po , next time I'll play with rebase. Thank you!

**Pull request closed without merging**
