### PR TITLE
system login: T874: add 2FA support for local and ssh authentication

### PR DESCRIPTION
**Pull request by goodNETnick**
Documentation for the authentication by using OTP 2FA.
T874

### CODE REVIEW

**Comment by goodNETnick** [comment]
Feature PR:
https://github.com/vyos/vyos-1x/pull/1555

**Review by dmbaturin — APPROVED** [review]

**Comment by rebortg** [comment]
will wait for feature merge

**Comment by c-po** [comment]
Would it be possible to get a full example of how to set this one up also using Google authenticator?

**Comment by goodNETnick** [comment]
Documentation PR updated

**Pull request merged**
